#!/bin/zsh -f

set -e

name=jobs
dir="$HOME/docs/work"

$HOME/.config/scripts/rename_workspace.sh $name
tmux new-session -ds $name -c $dir

tmux rename-window -t $name:1 notes
tmux send-keys -t "${name}:notes" nvim Enter

tmux new-window -t $name -n shell -c $dir

tmux attach -t ${name}:notes
