vim.api.nvim_create_user_command('TempMD', function()
    require('functions.temp').open_yank_buffer('markdown')
end, { nargs = '*' })

vim.api.nvim_create_user_command('SaveToCopy', function()
    vim.keymap.set('n', '<c-space>', function()
        vim.cmd('write')
        yank.file()
        vim.cmd('e#')
    end, { desc = 'Copy buffer', buffer = true })
end, { nargs = '*' })
