#!/bin/bash

# duplicate selection or current

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -f $sel ]
then
    files=$(cat $sel | tr '\0' '\n')
    for file in $files
    do
        cp $file ${file}.copy
    done
else
    cp -r $1 ${1}.copy
fi
