#!/usr/bin/env sh

view_fifo="$NNN_FIFO.view"
max_lines=$(($(tput lines) - 1))
echo $max_lines >$NNN_FIFO.max_lines

echo -ne '\e[?7l'
while true; do
    read -r command <$view_fifo
    max_lines=$(($(tput lines) - 1))
    echo $max_lines >$NNN_FIFO.max_lines
    clear
    eval $command | head --lines $max_lines
done
