local paths = require("lib.paths")

describe("lib.paths", function()
	it("extracts the basename of a path", function()
		assert.are.equal("c.lua", paths.basename("/a/b/c.lua"))
		assert.are.equal("file", paths.basename("file"))
		assert.are.equal("x", paths.basename("/a/b/x"))
	end)

	it("returns the last component of a path with no slash", function()
		assert.are.equal("init.lua", paths.basename("lua/core/init.lua"))
	end)

	it("reads the file name of the current buffer", function()
		vim.api.nvim_buf_set_name(0, "/tmp/example/widget.py")
		assert.are.equal("widget.py", paths.get_file_name())
	end)

	it("get_absolute_path returns the full path of the current buffer", function()
		vim.api.nvim_buf_set_name(0, "/home/user/project/foo.lua")
		assert.are.equal("/home/user/project/foo.lua", paths.get_absolute_path())
	end)

	it("get_absolute_directory returns the directory containing the buffer", function()
		vim.api.nvim_buf_set_name(0, "/home/user/project/src/foo.lua")
		assert.are.equal("/home/user/project/src", paths.get_absolute_directory())
	end)

	it("get_line returns the current cursor line number", function()
		vim.cmd("enew!")
		vim.api.nvim_buf_set_lines(0, 0, -1, false, { "a", "b", "c" })
		vim.api.nvim_win_set_cursor(0, { 3, 0 })
		assert.are.equal(3, paths.get_line())
	end)
end)
