#!/usr/bin/python

import json
import subprocess
import os

device_long = subprocess.check_output(["pactl", "get-default-source"]).strip().decode()

home = os.path.expanduser("~")
setup_dir = '.setup'
sources_name = 'sources.js'
sources_path = os.path.join(home, setup_dir, sources_name)
with open(sources_path, "r") as f:
    sources = json.load(f)
device_translator = { long: short for short, long in sources.items() }

device_short = device_translator.get(device_long, "unk")

print(device_short)
