#!/usr/bin/python

import json
import subprocess
import os

device_long = subprocess.check_output(["pactl", "get-default-sink"]).strip().decode()

home = os.path.expanduser("~")
setup_dir = '.setup'
sinks_name = 'sinks.js'
sinks_path = os.path.join(home, setup_dir, sinks_name)
with open(sinks_path, "r") as f:
    sinks = json.load(f)
device_translator = { long: short for short, long in sinks.items() }

device_short = device_translator.get(device_long, "unk")

print(device_short)
