#!/usr/bin/python

import json
import os
import subprocess
import sys

if len(sys.argv) == 1:
    print("oh no you didn't")
    sys.exit(1)

device_short = sys.argv[1]

home = os.path.expanduser("~")
setup_dir = '.setup'
sinks_name = 'sinks.js'
sinks_path = os.path.join(home, setup_dir, sinks_name)
with open(sinks_path, "r") as f:
    sinks = json.load(f)

device_long = sinks[device_short]

subprocess.run(["pactl", "set-default-sink", device_long])
