#!/usr/bin/python

import json
import subprocess
import os

device_long = subprocess.check_output(["pactl", "get-default-sink"]).strip().decode()

home = os.path.expanduser("~")
setup_dir = '.setup'
sound_devices_name = 'sound_devices'
sound_devices_path = os.path.join(home, setup_dir, sound_devices_name)
with open(sound_devices_path, "r") as f:
    sound_devices = json.load(f)
device_translator = { long: short for short, long in sound_devices.items() }

device_short = device_translator.get(device_long, "unk")

print(device_short)
