#!/usr/bin/python3

import os
import subprocess

home = os.path.expanduser("~")
setup_dir = ".setup"
ifname_name = "ifname"
ifname_path = os.path.join(home, setup_dir, ifname_name)
with open(ifname_path, "r") as f:
    ifname = f.read().strip()

command = f"iw dev {ifname} link | grep SSID | cut -d ' ' -f 2-"
ssid = subprocess.check_output(
    command, shell=True
).decode()

print(ssid)
