#!/bin/bash

tmux send-keys -t vim ":e src/trackProcessingService/debugANNGenerator.jl" Enter

tmux send-keys -t run.0 "repl julia" Enter
tmux send-keys -t run.1 "julia" Enter

tmux send-keys -t repl.0 "repl julia" Enter
tmux send-keys -t repl.1 "julia" Enter

tmux select-window -t vim
tmux kill-window -t setup
